[package]
name = "calculadora"
version = "0.1.0"
edition = "2024"
authors = ["astartesdeveloper@gmail.com"]

[profile.release]
opt-level= "z"
lto = true
codegen-units = 1 
panic = "abort"
strip = true 


